version: '{build}'

image: Visual Studio 2019

build_script:
- cmd: C:\go116\bin\go.exe run -mod=readonly ./cmd/kepubify --help

test_script:
- cmd: C:\go116\bin\go.exe test -mod=readonly -run "^TestMod_" golang.org/x/net/html -v
- cmd: C:\go116\bin\go.exe test -mod=readonly -v ./kepub
- cmd: C:\go116\bin\go.exe test -mod=readonly -v ./cmd/kepubify

deploy: off
