language: go
go: 
 - 1.8.3

script:
 - go get -v "github.com/kardianos/govendor"
 - go get -v "github.com/aktau/github-release"
 - govendor sync
 - go generate
 - go test -v ./...
 - go build

deploy:
  provider: script
  script: /bin/bash $TRAVIS_BUILD_DIR/release.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master