language: go
go: 
 - "1.12"

addons:
  apt:
    packages:
     - libsqlite3-dev
     - gcc-mingw-w64-i686

script:
 - export GO111MODULE=on
 - go get -v "github.com/aktau/github-release"
 - go get -v "github.com/goreleaser/nfpm/cmd/nfpm"
 - go generate ./...
 - go test -v ./...

deploy:
  provider: script
  script: /bin/bash $TRAVIS_BUILD_DIR/release.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master