os:
- osx

language: go

go:
- 1.16.x

script:
- go run -mod=readonly ./cmd/kepubify --help
- go test -mod=readonly -run "^TestMod_" github.com/pgaskin/kepubify/_/html/golang.org/x/net/html -v
- go test -mod=readonly -v ./kepub
- go test -mod=readonly -v -tags zip117 ./kepub
- go test -mod=readonly -v ./cmd/kepubify
