name: forks - go116-zip.go117
on: [push, pull_request]

jobs:
  test:
    name: test - Go ${{matrix.go}}
    runs-on: ubuntu-latest
    container: golang:${{matrix.go}}-alpine
    strategy:
      matrix:
        go:
          - 1.16
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: |
          cd _/go116-zip.go117 && go test -v ./...
